version: '3'
services:
  mongo:
    image: 'mongo:4.4'
  redis:
    image: 'redis:6.2'
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - data:/app
    working_dir: /app
    user: ${MY_USER:-root}
    depends_on:
      - redis
      - mongo
    command: 'bash ./test.sh'
volumes:
  data:
