name: Veterinary Authorizer

on: [push]

# env:
#   DEFAULT_DB: veterinary-authorizer
#   MONGODB_URI: mongodb://localhost:27017
#   JWT_SECRET_KEY: abc4efghijklm6opqrstuvwxyzABCDEFGHIJ6LMNOPQRSTU9WXYZ0123456789
#   REDIS_URI: localhost:6379

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          docker-compose up --abort-on-container-exit --exit-code-from test
      # - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      #   uses: actions/setup-dotnet@v1.7.2
      #   with:
      #     dotnet-version: ${{ matrix.dotnet-version }}
      # - name: Install dependencies
      #   run: dotnet restore
      # - name: Build
      #   run: dotnet build
      # - name: Test
      #   run: dotnet test
